### ISSUE TITLE
replace iced-coffee-script code with coffeescript 2

### ISSUE THREAD

**Issue by joaomlneto** [joaomlneto/antidote-rest-server#7]

**Comment by rogerpueyo** [comment]
https://github.com/joaomlneto/antidote-rest-server/blob/master/README.md still mentions iced-coffee-script :face_with_head_bandage:

**Comment by joaomlneto** [comment]
Hey! :) thanks!

I forgot that part.
No need for coffeescript/icedcoffeescript to run the server — vanilla node.js should be enough. 

Let me know if I broke something. 
BTW are you still using it at UPC?
